### ISSUE TITLE
How to map phenotype ID to regions?

### ISSUE THREAD

**Issue by WeiCSong** [BIG-S2/GWAS#1]
Hi,
   I noticed that in dropbox, all files were named as pheno1, pheno2... etc., and in supplementary table of your paper, you ordered all regions alphabetically. i assumed that they are correponded, i.e. pheno1 is  left.caudal.anterior.cingulate, am i right? Or where can i obtain their mapping relationship?  Thank you for your help.

Best,

Weichen Song

**Comment by BIG-S2** [comment]
Hi, Weichen, 
we are so sorry for the late response. 

The phenotypes are not the regions in alphabetical order. You can find ROI names of pheno1~pheono101 at https://www.med.unc.edu/bigs2/files/2019/05/gwas_ROI_v20190524.xlsx
(Sheet tab "ID")

**Comment by WeiCSong** [comment]
Got it, thanks!
